export const defaultModifiers = {
  hover: "&:hover",
  focus: "&:focus",
  focusWithin: "&:focus-within",
  focusVisible: "&:focus-visible",
  active: "&:active",
  visited: "&:visited",
  target: "&:target",
  first: "&:first-child",
  last: "&:last-child",
  only: "&:only-child",
  odd: "&:nth-child(odd)",
  even: "&:nth-child(even)",
  firstOfType: "&:first-of-type",
  lastOfType: "&:last-of-type",
  onlyOfType: "&:only-of-type",
  empty: "&:empty",
  disabled: "&:disabled",
  checked: "&:checked",
  indeterminate: "&:indeterminate",
  default: "&:default",
  required: "&:required",
  valid: "&:valid",
  invalid: "&:invalid",
  inRange: "&:in-range",
  outOfRange: "&:out-of-range",
  placeholderShown: "&:placeholder-shown",
  autoFill: "&:autofill",
  readOnly: "&:read-only",
  open: "&[open]",
  before: "&::before",
  after: "&::after",
  firstLetter: "&::first-letter",
  firstLine: "&::first-line",
  marker: "&::marker",
  selection: "&::selection",
  file: "&::file-selector-button",
  placeholder: "&::placeholder",
  sm: "@media (min-width: 640px)",
  md: "@media (min-width: 768px)",
  lg: "@media (min-width: 1024px)",
  xl: "@media (min-width: 1280px)",
  "2xl": "@media (min-width: 1536px)",
  dark: "@media (prefers-color-scheme: dark)",
  portrait: "@media (orientation: portrait)",
  landscape: "@media (orientation: landscape)",
  motionSafe: "@media (prefers-reduced-motion: no-preference)",
  motionReduce: "@media (prefers-reduced-motion: reduce)",
  print: "@media print",
  rtl: "[dir=“rtl”] &",
  ltr: "[dir=“ltr”] &",
};
